[package]
name = "PQC_kyber"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-kyber = "0.7.9"
pqcrypto-traits = "0.3.5"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["serde", "pem"] }
rand_core = "0.6.4"
secrecy = "0.8"
serde = { version = "1.0", features = ["derive"] }
indicatif = "0.17.7"
p256 = { version = "0.13.2", features = ["ecdh"] }
actix-web = "4.3.1"
serde_json = "1.0"
base64 = "0.13"
env_logger = "0.9"
rayon = "1.7"
mimalloc = "0.1"
metrics = "0.20"
tracing = "0.1"
csv = "1.3.1"
once_cell = "1.8"
uuid = { version = "1.0", features = ["v4"] }
zeroize = { version = "1.5", features = ["zeroize_derive"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
parking_lot = "0.12"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"


[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.2"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

