# Extended CI/CD Pipeline for Post-Quantum Cryptography (PQC)
name: PQC Integration CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pqc-tests:
    name: Run PQC Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # Updated OQS repository setup
      - name: Set up OQS repository
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget
          # Download and install OQS repository key
          sudo mkdir -p /etc/apt/keyrings
          wget -O - https://openquantumsafe.org/repo/ubuntu/KEY.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/oqs.gpg
          # Add OQS repository
          echo "deb [signed-by=/etc/apt/keyrings/oqs.gpg] https://openquantumsafe.org/repo/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/oqs.list
          sudo apt-get update

      - name: Install liboqs
        run: |
          sudo apt-get install -y liboqs-dev
          # Verify installation
          if ! dpkg -l | grep -q liboqs-dev; then
            echo "liboqs-dev installation failed"
            exit 1
          fi

      - name: Run PQC tests
        run: cargo test --features pqc

      - name: Run PQC benchmarks
        run: cargo bench --features pqc